In [1]:
import numpy as np


sudoku = [[0,6,0,0,3,5,0,4,0],
          [3,8,2,0,0,0,0,0,0],
          [0,0,0,0,0,1,0,0,6],
          [0,0,0,0,1,2,8,0,0],
          [0,0,9,0,8,0,7,0,4],
          [0,0,6,0,0,0,0,0,0],
          [0,9,0,4,0,0,1,0,2],
          [0,3,0,5,0,0,0,0,9],
          [0,4,0,0,0,3,0,0,5]]

print(np.matrix(sudoku))

[[0 6 0 0 3 5 0 4 0]
 [3 8 2 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 6]
 [0 0 0 0 1 2 8 0 0]
 [0 0 9 0 8 0 7 0 4]
 [0 0 6 0 0 0 0 0 0]
 [0 9 0 4 0 0 1 0 2]
 [0 3 0 5 0 0 0 0 9]
 [0 4 0 0 0 3 0 0 5]]


In [2]:
def possible (x,y,n):
    global sudoku
    
    # checkt die Reihe
    for i in range (0,9):
        if sudoku[y][i] == n:
            return False
    
    # checkt die Spalte
    for i in range (0,9):
        if sudoku[i][x] == n:
            return False
        
    # checkt den Block    
    x0 = (x//3)*3
    y0 = (y//3)*3
    
    for i in range (0,3):
        for j in range (0,3):
            if sudoku[y0+i][x0+j] == n:
                return False
    return True

possible(0,0,9)

True

In [ ]:
def solve():
    global sudoku
    
    for y in range(9):
        for x in range(9):
            if sudoku[y][x] == 0:
                for n in range(1,10):
                    if possible(y,x,n):
                        sudoku[y][x] = n
                        solve()
                        sudoku[y][x] = 0
                return
    print(np.matrix(sudoku))
    input("More?")
    
solve()